CREATE TABLE IF NOT EXISTS `users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `unionId` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `department` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `avatar` TEXT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `passwordHash` VARCHAR(255) NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `lastSignInAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_unionId_unique` (`unionId`),
  KEY `users_role_idx` (`role`),
  KEY `users_department_idx` (`department`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(255) NOT NULL,
  `projectCode` VARCHAR(255) NULL,
  `projectType` VARCHAR(255) NULL,
  `specialty` VARCHAR(255) NULL,
  `projectManagerId` INT NULL,
  `assigneeId` INT NULL,
  `status` ENUM('todo', 'in_progress', 'review', 'done') NOT NULL DEFAULT 'todo',
  `priority` ENUM('low', 'medium', 'high', 'urgent') NOT NULL DEFAULT 'medium',
  `plannedStartDate` VARCHAR(10) NULL,
  `plannedEndDate` VARCHAR(10) NULL,
  `estimatedHours` INT NULL,
  `remark` TEXT NULL,
  `creatorId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `tasks_status_idx` (`status`),
  KEY `tasks_priority_idx` (`priority`),
  KEY `tasks_assignee_idx` (`assigneeId`),
  KEY `tasks_creator_idx` (`creatorId`),
  KEY `tasks_project_manager_idx` (`projectManagerId`),
  CONSTRAINT `tasks_project_manager_fk` FOREIGN KEY (`projectManagerId`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tasks_assignee_fk` FOREIGN KEY (`assigneeId`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `tasks_creator_fk` FOREIGN KEY (`creatorId`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM(
    'task_created',
    'task_updated',
    'task_assigned',
    'task_completed',
    'task_deleted',
    'status_changed',
    'user_created',
    'user_updated',
    'user_deleted',
    'user_imported',
    'leave_created',
    'leave_deleted',
    'leave_status_changed',
    'trip_created',
    'trip_updated',
    'trip_deleted',
    'trip_imported'
  ) NOT NULL,
  `description` TEXT NOT NULL,
  `userId` INT NULL,
  `taskId` INT NULL,
  `before_json` TEXT NULL,
  `after_json` TEXT NULL,
  `ip_address` VARCHAR(255) NULL,
  `user_agent` TEXT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `activities_type_idx` (`type`),
  KEY `activities_user_idx` (`userId`),
  KEY `activities_task_idx` (`taskId`),
  KEY `activities_created_at_idx` (`createdAt`),
  CONSTRAINT `activities_user_fk` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `activities_task_fk` FOREIGN KEY (`taskId`) REFERENCES `tasks` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `attendances` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `type` ENUM('sick', 'annual', 'personal', 'marriage', 'maternity', 'other') NOT NULL DEFAULT 'other',
  `startDate` VARCHAR(10) NOT NULL,
  `endDate` VARCHAR(10) NOT NULL,
  `days` INT NULL,
  `reason` TEXT NULL,
  `status` ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
  `approvedBy` INT NULL,
  `approvedAt` DATETIME NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `attendances_user_idx` (`userId`),
  KEY `attendances_status_idx` (`status`),
  KEY `attendances_start_date_idx` (`startDate`),
  CONSTRAINT `attendances_user_fk` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `attendances_approved_by_fk` FOREIGN KEY (`approvedBy`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `business_trip` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `employee_name` VARCHAR(255) NOT NULL,
  `department` VARCHAR(255) NOT NULL,
  `project_code` VARCHAR(255) NOT NULL,
  `cycle_start` VARCHAR(10) NOT NULL,
  `cycle_end` VARCHAR(10) NOT NULL,
  `dispatch_start` VARCHAR(10) NOT NULL DEFAULT '',
  `dispatch_end` VARCHAR(10) NOT NULL DEFAULT '',
  `location` VARCHAR(255) NOT NULL,
  `work_days` INT NOT NULL,
  `actual_days` INT NOT NULL,
  `office_days` INT NOT NULL,
  `trip_days` INT NOT NULL,
  `temp_days` INT NOT NULL,
  `absence_days` INT NOT NULL,
  `absence_reason` TEXT NULL,
  `subsidy_days` INT NOT NULL,
  `remark` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  KEY `business_trip_user_id_idx` (`user_id`),
  KEY `business_trip_department_idx` (`department`),
  KEY `business_trip_cycle_start_idx` (`cycle_start`),
  CONSTRAINT `business_trip_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `system_settings` (
  `key` VARCHAR(191) NOT NULL,
  `value` TEXT NOT NULL,
  `is_encrypted` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_by` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key`),
  CONSTRAINT `system_settings_updated_by_fk` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
